import Foundation
import Darwin

@MainActor enum TerminalSetupTests {
    static func run() async throws {
        let root = FileManager.default.temporaryDirectory.resolvingSymlinksInPath().appendingPathComponent("orbit-terminal-test-" + UUID().uuidString)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        func home(_ name: String) throws -> URL { let url = root.appendingPathComponent(name); try FileManager.default.createDirectory(at: url, withIntermediateDirectories: false); return url }
        let directory = try home("roundtrip"), engine = ProfileEngine(home: directory)
        let original = Data("# keep my private setup\nexport CUSTOM_SETTING='unchanged'\n".utf8)
        try original.write(to: directory.appendingPathComponent(".zshrc"))
        try FileManager.default.setAttributes([.posixPermissions: 0o640], ofItemAtPath: directory.appendingPathComponent(".zshrc").path)
        let selected = Set(TerminalOption.all.map(\.id)).subtracting(["git-identity", "prompt-theme", "custom-aliases"])
        let plan = try engine.plan(selected)
        precondition(plan.changes.count == 2 && !FileManager.default.fileExists(atPath: directory.appendingPathComponent(".zprofile").path))
        try engine.validate(plan)
        let backup = try engine.apply(plan)
        let rc = try String(contentsOf: directory.appendingPathComponent(".zshrc"), encoding: .utf8)
        precondition(rc.hasPrefix(String(data: original, encoding: .utf8)!))
        precondition(rc.components(separatedBy: ProfileEngine.begin).count == 2)
        precondition(try! engine.plan(selected).changes.isEmpty, "Repeat apply must not duplicate blocks")
        let receiptAttributes = try FileManager.default.attributesOfItem(atPath: backup.appendingPathComponent("receipt.json").path)
        precondition(receiptAttributes[.posixPermissions] as? Int == 0o600)
        try engine.restore()
        precondition(try! Data(contentsOf: directory.appendingPathComponent(".zshrc")) == original)
        precondition(!FileManager.default.fileExists(atPath: directory.appendingPathComponent(".zprofile").path), "Originally absent profiles must be removed on restore")
        precondition(try! engine.inspect(".zshrc").permissions == 0o640)
        _ = try engine.apply(engine.plan(["history"]))
        let changed = try engine.plan(["aliases"])
        _ = try engine.apply(changed)
        let replaced = try String(contentsOf: directory.appendingPathComponent(".zshrc"), encoding: .utf8)
        precondition(!replaced.contains("orbit-option: history") && replaced.contains("orbit-option: aliases"))
        let current = try engine.inspect(".zshrc").data!
        try (current + Data("# user edit\n".utf8)).write(to: directory.appendingPathComponent(".zshrc"))
        precondition((try? engine.restore()) == nil, "Post-apply edits must block restore")
        let permissionHome = try home("permission-edit"), permission = ProfileEngine(home: permissionHome)
        _ = try permission.apply(permission.plan(["history"]))
        try FileManager.default.setAttributes([.posixPermissions: 0o644], ofItemAtPath: permissionHome.appendingPathComponent(".zshrc").path)
        precondition((try? permission.restore()) == nil, "Post-apply permission changes must also block restore")
        let staleHome = try home("stale"), stale = ProfileEngine(home: staleHome)
        let stalePlan = try stale.plan(["history"])
        try Data("export KEEP=1\n".utf8).write(to: staleHome.appendingPathComponent(".zshrc"))
        precondition((try? stale.apply(stalePlan)) == nil)
        precondition(try! String(contentsOf: staleHome.appendingPathComponent(".zshrc"), encoding: .utf8) == "export KEEP=1\n")
        let envHome = try home("env-change"), env = ProfileEngine(home: envHome)
        let envPlan = try env.plan(["python"])
        try Data("export ZDOTDIR=/another/place\n".utf8).write(to: envHome.appendingPathComponent(".zshenv"))
        precondition((try? env.apply(envPlan)) == nil)
        let largeHome = try home("large"), large = ProfileEngine(home: largeHome)
        try Data(("#" + String(repeating: "x", count: 999_995) + "\n").utf8).write(to: largeHome.appendingPathComponent(".zshrc"))
        precondition((try? large.plan(["history"])) == nil, "Apply must never produce an oversized, unrestorable profile")
        let invalidHome = try home("invalid"), invalid = ProfileEngine(home: invalidHome)
        try Data("if then\n".utf8).write(to: invalidHome.appendingPathComponent(".zshrc"))
        precondition((try? invalid.apply(invalid.plan(["history"]))) == nil, "Syntax error must leave files untouched")
        let linkHome = try home("links"), link = ProfileEngine(home: linkHome)
        let target = root.appendingPathComponent("target"); try Data("untouched".utf8).write(to: target)
        try FileManager.default.createSymbolicLink(at: linkHome.appendingPathComponent(".zshrc"), withDestinationURL: target)
        precondition((try? link.plan(["history"])) == nil)
        try FileManager.default.removeItem(at: linkHome.appendingPathComponent(".zshrc"))
        precondition(Darwin.link(target.path, linkHome.appendingPathComponent(".zshrc").path) == 0)
        precondition((try? link.plan(["history"])) == nil, "Hard-linked profiles must be blocked")
        let backupHome = try home("backup-link"), blocked = ProfileEngine(home: backupHome)
        try FileManager.default.createSymbolicLink(at: blocked.backupRoot, withDestinationURL: root)
        precondition((try? blocked.apply(blocked.plan(["history"]))) == nil)
        precondition((try? ProfileEngine.split(ProfileEngine.begin)) == nil)
        precondition((try? ProfileEngine.split(ProfileEngine.begin + "\n" + ProfileEngine.end + "\n" + ProfileEngine.begin + "\n" + ProfileEngine.end)) == nil)
        let existingHome = try home("existing"), existing = ProfileEngine(home: existingHome)
        try Data("export NVM_DIR=\"$HOME/.nvm\"\neval \"$(starship init zsh)\"\n".utf8).write(to: existingHome.appendingPathComponent(".zshrc"))
        precondition((try? existing.plan(["node"])) == nil && (try? existing.plan(["starship"])) == nil)
        precondition(ProfileEngine.conflicts(TerminalOption.all.first { $0.id == "python" }!, outside: "oa() { echo custom; }"))
        let state = TerminalState(engine: existing); state.scan()
        precondition(state.scanned && !state.selected.contains("node"))
        let runtimeOptions = TerminalOption.all.filter { $0.group == "Languages" }
        precondition(Set(runtimeOptions.map(\.id)) == ["node", "python", "java", "go", "rust", "ruby"])
        precondition(!TerminalOption.all.flatMap(\.packages).contains("node") && !TerminalOption.all.flatMap(\.packages).contains("corepack") && !TerminalOption.all.flatMap(\.packages).contains("ruby-build"))
        let noExecuteHome = try home("no-execution"), noExecute = ProfileEngine(home: noExecuteHome)
        let marker = root.appendingPathComponent("must-not-exist")
        try Data("touch '\(marker.path)'\n".utf8).write(to: noExecuteHome.appendingPathComponent(".zshrc"))
        try noExecute.validate(noExecute.plan(["history"]))
        precondition(!FileManager.default.fileExists(atPath: marker.path), "Syntax validation must never execute user code")
        let model = Store(preview: true); model.navigate(.terminal)
        precondition(model.mode == .terminal)
        let fixture = try OfficialCatalog.parse(Data(#"[{"name":"fixture-terminal","tap":"homebrew/core","desc":"fixture","homepage":"https://example.com","versions":{"stable":"1.0"}}]"#.utf8), cask: false)[0]
        let queueModel = Store(persistSelection: false); queueModel.selected = []; queueModel.appPresent = { _ in false }; queueModel.inventoryKnown = true
        let noCommands = FakeCommands([]); queueModel.commandRunner = noCommands
        let queue = TerminalState(engine: engine, packageLoader: { _ in fixture }); queue.missing = [fixture.token]
        await queue.queuePackages(store: queueModel)
        let commandCalls = await noCommands.recorded(); precondition(commandCalls.isEmpty)
        precondition(queueModel.selected == [fixture.id] && queueModel.packages.contains { $0.id == fixture.id } && queueModel.mode == .install)
        precondition(Catalog.export(queueModel.packages.filter { queueModel.selected.contains($0.id) }).contains("fixture-terminal"))
        let failed = TerminalState(engine: engine, packageLoader: { token in if token == fixture.token { return fixture }; throw ProfileProblem(message: "offline") })
        failed.missing = [fixture.token, "missing-fixture"]
        queueModel.selected = []; queueModel.navigate(.terminal)
        let count = queueModel.packages.count
        await failed.queuePackages(store: queueModel)
        precondition(queueModel.selected.isEmpty && queueModel.packages.count == count && queueModel.mode == .terminal)
        let busy = TerminalState(engine: engine, packageLoader: { _ in queueModel.preparing = true; return fixture }); busy.missing = [fixture.token]
        await busy.queuePackages(store: queueModel)
        precondition(queueModel.selected.isEmpty, "A changing installation state must block package registration")
        queueModel.preparing = false
        // Extended setup uses disposable homes only; no developer environment changes.
        let extendedHome = try home("extended"), extended = ProfileEngine(home: extendedHome)
        var config = TerminalConfiguration(); config.gitName = "Example Developer"; config.gitEmail = "example@example.com"; config.pythonVersion = "3.12"; config.javaVersion = "17"; config.theme = "Developer"
        config.aliases = [.init(name: "projectstatus", command: "echo 'hello' $(touch '\(marker.path)')")]
        let gitOriginal = Data("[core]\n\teditor = vim\n[user]\n\tname = Old\n\temail = old@example.com\n".utf8)
        try gitOriginal.write(to: extendedHome.appendingPathComponent(".gitconfig"))
        let extendedSelection: Set<String> = ["brew", "python", "java", "starship", "prompt-theme", "custom-aliases", "git-identity", "highlighting"]
        let extendedPlan = try extended.plan(extendedSelection, configuration: config)
        precondition(extendedPlan.changes.count == 4)
        try extended.validate(extendedPlan)
        precondition(!FileManager.default.fileExists(atPath: marker.path), "Custom alias bodies must not execute during review")
        _ = try extended.apply(extendedPlan)
        let extendedRC = try String(contentsOf: extendedHome.appendingPathComponent(".zshrc"), encoding: .utf8)
        precondition(extendedRC.contains("--python '3.12'") && extendedRC.contains("openjdk@17"))
        precondition(extendedRC.range(of: "STARSHIP_CONFIG")!.lowerBound < extendedRC.range(of: "starship init")!.lowerBound)
        precondition(extendedRC.hasSuffix("zsh-syntax-highlighting.zsh\"\n" + ProfileEngine.end + "\n"))
        let gitAfter = try String(contentsOf: extendedHome.appendingPathComponent(".gitconfig"), encoding: .utf8)
        precondition(gitAfter.contains("editor = vim") && gitAfter.contains("example@example.com"))
        precondition(try! extended.plan(extendedSelection, configuration: config).changes.isEmpty)
        try extended.restore()
        precondition(try! Data(contentsOf: extendedHome.appendingPathComponent(".gitconfig")) == gitOriginal)
        precondition(!FileManager.default.fileExists(atPath: extendedHome.appendingPathComponent(".orbit-starship.toml").path))
        let collisions = try home("alias-collisions"), collisionEngine = ProfileEngine(home: collisions)
        try Data("alias projectstatus='existing'\n".utf8).write(to: collisions.appendingPathComponent(".zshrc"))
        precondition((try? collisionEngine.plan(["custom-aliases"], configuration: config)) == nil)
        var injection = config; injection.nodeVersion = "22; touch /tmp/no"; precondition((try? injection.validate()) == nil)
        injection = config; injection.aliases = [.init(name: "bad;name", command: "echo hi")]; precondition((try? injection.validate()) == nil)
        injection = config; injection.aliases = [.init(name: "okname", command: "echo hi\necho no")]; precondition((try? injection.validate()) == nil)
        injection = config; injection.gitName = "bad\n[credential]"; precondition((try? injection.validate()) == nil)
        let transfer = TerminalTransfer(selected: ["python", "node"], configuration: TerminalConfiguration())
        let decoded = try JSONDecoder().decode(TerminalTransfer.self, from: JSONEncoder().encode(transfer)); try decoded.validate()
        var invalidTransfer = transfer; invalidTransfer.version = 99; precondition((try? invalidTransfer.validate()) == nil)
        let projectHome = try home("project")
        try Data("20.12.0\n".utf8).write(to: projectHome.appendingPathComponent(".nvmrc"))
        try Data("3.12\n".utf8).write(to: projectHome.appendingPathComponent(".python-version"))
        try Data(#"{"packageManager":"pnpm@9.15.0","engines":{"node":">=20"},"scripts":{"postinstall":"touch NEVER"}}"#.utf8).write(to: projectHome.appendingPathComponent("package.json"))
        try Data("requires-python = \">=3.12\"\n".utf8).write(to: projectHome.appendingPathComponent("pyproject.toml"))
        let requirement = try TerminalProject.read(projectHome)
        precondition(requirement.node == "20.12.0" && requirement.python == "3.12" && requirement.manager == "pnpm" && requirement.managerVersion == "9.15.0")
        let customState = TerminalState(engine: extended); customState.scan(); customState.configuration = config; customState.selected = ["node", "python", "rust", "ruby"]; customState.runtimeChoices = customState.selected; customState.configuration.packageManager = "pnpm"; customState.configuration.packageManagerVersion = "9.15.0"
        let script = try customState.runtimeScript()
        precondition(script.contains("nvm install --lts") && script.contains("uv python install '3.12'") && script.contains("pnpm@9.15.0") && !script.contains(".zshrc") && !script.contains("corepack"))
        let scriptFile = root.appendingPathComponent("runtime-commands.zsh"); try Data(script.utf8).write(to: scriptFile)
        let syntax = Process(); syntax.executableURL = URL(fileURLWithPath: "/bin/zsh"); syntax.arguments = ["-f", "-n", scriptFile.path]; try syntax.run(); syntax.waitUntilExit(); precondition(syntax.terminationStatus == 0)
        customState.inspectProject(projectHome); customState.useProjectVersions(); precondition(customState.configuration.nodeVersion == "20.12.0")
        customState.configuration.packageManager = "Yarn"; customState.configuration.packageManagerVersion = "4.0.0"; precondition(try! customState.runtimeScript().contains("@yarnpkg/cli-dist@4.0.0"))
        customState.configuration.packageManager = "npm"; customState.choosePreset("Minimal"); precondition(customState.selected == TerminalOption.essentials)
        let suite = "orbit-terminal-fixture-" + UUID().uuidString, prefs = UserDefaults(suiteName: suite)!
        defer { prefs.removePersistentDomain(forName: suite) }
        let persisted = TerminalState(engine: extended, preferences: prefs); persisted.scan(); persisted.configuration = config; persisted.selected = ["python"]; persisted.review(); persisted.apply()
        precondition(TerminalState(engine: extended, preferences: prefs).configuration.pythonVersion == "3.12")
        precondition(!FileManager.default.fileExists(atPath: marker.path))
        queueModel.terminalState.working = true; precondition(queueModel.locked); queueModel.terminalState.working = false
        let portable = TerminalTransfer.portable(selected: extendedSelection, configuration: config)
        precondition(portable.configuration.gitName.isEmpty && portable.configuration.gitEmail.isEmpty && portable.configuration.aliases.isEmpty && !portable.selected.contains("custom-aliases") && !portable.selected.contains("git-identity"))
        customState.configuration.packageManager = "npm"; customState.runtimeChoices = ["python"]; customState.reviewRuntimes()
        let fakeRuntimes = FakeCommands([(0, "fixture download completed")]); queueModel.commandRunner = fakeRuntimes
        await customState.runRuntimes(store: queueModel)
        let runtimeCalls = await fakeRuntimes.recorded(); precondition(runtimeCalls.count == 1 && runtimeCalls[0].prefix(2) == ["-f", "-c"] && !customState.working && customState.runtimeReview == nil)
        customState.reviewRuntimes(); customState.configuration.pythonVersion = "3.11"; await customState.runRuntimes(store: queueModel)
        let unchangedCalls = await fakeRuntimes.recorded(); precondition(unchangedCalls.count == 1, "Changing choices must invalidate reviewed downloads")
        let probe = await TerminalState.probe("/usr/bin/true", arguments: []); precondition(probe.0 == 0)
        print("PASS: configurable runtime plans, inert aliases, Git/theme private backups, managed block ordering, portable setup validation, read-only project metadata and saved configuration")
        if CommandLine.arguments.contains("--live-terminal-metadata") {
            let tokens = Set(TerminalOption.all.flatMap(\.packages)).union(["openjdk@17", "openjdk@25"]).sorted()
            for token in tokens { let verified = try await TerminalState.fetchPackage(token); precondition(verified.token == token && verified.installable) }
            print("PASS: live official metadata for \(tokens.count) optional terminal tools; no installation")
        }
        print("PASS: terminal plan review, profile preservation, private backups, idempotence, restore, edited/stale/symlink/hardlink/custom-directory protection, syntax-only validation, language choices and no direct dependencies")
    }
}
